#%RAML 1.0 NamedExample
{
  "crmId": "66666666",
  "referrerEmail":"ch+12@blendtest.com",
  "loanType":"HELOC",
  "borrower": {
    "name": {
      "firstName": "Bailey",
      "lastName": "Borrower"
    },
    "email": "ddddd@test.com",
    "homePhone": "111-222-3344",
    "dateOfBirth": "1990-01-01",
    "currentAddress": {
      "streetAddressLine1": "415 Kearny St",
      "city": "San Francisco",
      "state": "CA",
      "zipCode": "94108"
    }
  },
  "loanPurposeType": "PURCHASE",
  "loanAmount": "500000",
  "propertyValue": "450000",
  "propertyAddress": {
    "streetAddressLine1": "500 Pine St",
    "city": "San Francisco",
    "state": "CA",
    "zipCode": "94109"
  },
  "sendEmailInvite": false
}