#%RAML 1.0 SecurityScheme
type: Basic Authentication
describedBy: 
  headers: 
    Authorization:
      description: Base64-encoded "username:password"
      type: string
  responses: 
    401: 
      description: |
         Unauthorized: username or password or the combination is invalid